######################## default configuration ####################
baseURL = "https://AseLaw1.github.com/LeyesDiscapacitados"
languageCode = "en-us"
title = "Asesor de Leyes de Discapacitados"
theme = "LeyesDiscap"
publishDir = "docs"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Price"
URL = "price"
weight = 4

[[menu.main]]
name = "News"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Contact Us"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "IVONNE CASTRO"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright 2021 Designed by Ivonne Castro."

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "INFORMACIÓN DE <span>CONTACTO</span> "
blogTitle = "ÚLTIMOS<span>POST</span>"
galleryTitle = "FOTOS <span></span>"
socialTitle = "Síguenos <span></span>"
############################ footer contact item
[[params.footer.contactItem]]
title="Teléfono"
icon = "fa fa-phone"
content = "PBX: 046014080 / 046001590"

[[params.footer.contactItem]]
title="Dirección"
icon = "fa fa-map-marker"
content = "Av. 9 de octubre y av Tungurahua, Ecuador - Guayaquil "

[[params.footer.contactItem]]
title="E-mail"
icon = "fa fa-envelope"
content = "info@asesoronline.edu.ec"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-5.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-6.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://twitter.com/"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/"